###
# EXAMPLE CONFIG FILE
###

# All values in this file are expressed as strings
# and will be converted to the correct type when the service is started


# ETH node address. Websockets must be enabled.
eth_node: "ws://localhost:8545"

# Private key for signing transactions.
# The address derived from this key will need to have an ETH balance to pay for Transaction Gas.
eth_private_key: "0x89ee060717762819b0dfa501d1f3c246f059fd70a1b54c7231e617b32594e555"

# Payment Address -- (Optional) The ETH address where you want payments to be made.
# If no payment address is provided, the address derived from the eth_private_key will be used.
# payment_address: 0x...

# Mnemonic used to generate wallet which will be used for generating public/private key pairs
# Generate one here -- https://iancoleman.io/bip39/
mnemonic: "index cupboard city neither axis spot thumb pet rabbit stuff culture project top fault wisdom"

# Full path (including filename) to your arweave wallet key
arweave_key_file: "$GOPATH/bin/arweave.json"

# Arweave node address
# Defaults to Arweave's public node
# If using rootmos/loom docker image to test locally, you can use: http://localhost:8000/arweave
arweave_node: "https://arweave.net:443"

# Arweave fee multiplier
# Must have 1 decimal and quotes
# The node you are connected to will estimate arweave winston fee to use when sending the file to arweave
# However, you can increase this fee by using the multiplier (e.g. fee = 10, multiplier = 1.5, final fee = 15)
arweave_multiplier: "1.0"

# Sarcophagus Contract Address
# Currently set to Rinkeby Address
# Mainnet Address: 0xD227e63E7d74Ba0374E1d5B2479666b21ba7811c
contract_address: "0x939BE928b0d5fBb7f3FA07217c816496FcBEBa46"

# Sarcophagus Token Contract Address
# Currently set to Rinkeby Address
# Mainnet Address: 0x7697b462a7c4ff5f8b55bdbc2f4076c2af9cf51a
token_address: "0x77ec161f6c2f2ce4554695a07e071d3f0ef3aef5"

# Endpoint domain to be exposed for receiving a sarcophagus asset file
# Must use https
# You are responsible for exposing this endpoint and mapping it to your localhost port specified by file_port
endpoint: "https://myarch.sarcophagus.io"

# The file port that will be opened to receive the sarcophagus asset file
file_port: "8080"

# Used to calculate the storage fee you expect to receive for doing a Sarcophagus job.
# The minimum storage fee will be calculated as: fee_per_byte * file_bytes_size
# Expressed in SARCO Tokens with up to 18 decimals.
# Default is 0.000010000000000000 (.00001 SARCO Tokens)
fee_per_byte: "0.000010000000000000"

# The minimum amount of SARCO Tokens you want to receive for completing a Sarcophagus job.
# Expressed in SARCO Tokens with up to 18 decimals
# This is a 1-time payment that will be paid when a Sarcophagus job is complete (when the Sarcophagus is unwrapped).
# Default is 100.000000000000000000 (100 SARCO Tokens)
min_bounty: "100.000000000000000000"

# The minimum amount of SARCO Tokens you want to receive as a digging fee when a Sarcophagus is rewrapped.
# Expressed in SARCO Tokens with up to 18 decimals
# Default is 10.000000000000000000 (10 SARCO Tokens)
min_digging_fee: "10.000000000000000000"

# MAX_RESURRECTION_TIME is the relative time interval (in seconds) from the creation or rewrapping of the sarcophagus that you are willing to accept jobs within.
# For example, if you set max_resurrection_time to 1 month -- when a sarcophagus is created, the resurrection time set by the embalmer cannot be greater than 1 month in the future for you to accept the job.
# Expressed in Seconds (1 year = 31536000)
max_resurrection_time: "31536000"

# When the service starts, the value here will be added to your "Free Bond" on the Sarcophagus Contract
# This SARCO will be transferred from the address derived from the eth_private_key config value, so you must have enough a SARCO balance to cover this amount.  
# You must have Free Bond available on the Sarcophagus Contract to accept new jobs.
# Expressed in SARCO Tokens with up to 18 decimals
# This number will be reset to 0 after the service is started, so it must be manually set before running the service each time you want to deposit to free bond.
# Default is 100.000000000000000000 (100 SARCO Tokens)
add_to_free_bond: "100.000000000000000000"

# Expressed in SARCO Tokens with up to 18 decimals
# Type: String (expressed as decimal, must use quotes)
# Set as a string to allow for 18 decimals when config gets parsed.
# When the service starts, the number here will be subtracted from your "Free Bond" on the Sarcophagus Contract
# This number will be reset to 0 after the service is started, so it must be manually set before running the service each time you want to withdraw from free bond.
remove_from_free_bond: "0"